//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newColleagues
    {
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string phon { get; set; }
        public Nullable<int> areaId { get; set; }
        public Nullable<int> fieldId { get; set; }
        public Nullable<int> numHours { get; set; }
    
        public virtual areas areas { get; set; }
        public virtual fields fields { get; set; }
    }
}
